services:
  nginxwebsvr:
    image: nginx:alpine
    container_name: nginxwebsvrlab5quizprep
    ports:
      - "80:80"
    volumes:
      ### Mounting the necessary files
      - ./index.html:/usr/share/nginx/html/index.html
      - ./test.html:/usr/share/nginx/html/test.html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ### mounting all files
    ## - ./:/usr/share/nginx/html
