name: Test Nginx Hello World Page

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Nginx with Docker
        run: |
          docker run -d --name test-nginx -p 8080:80 \
            -v ${{ github.workspace }}/test.html:/usr/share/nginx/html/test.html:ro \
            -v ${{ github.workspace }}/nginx.conf:/etc/nginx/nginx.conf:ro \
            nginx:latest

      - name: Wait for Nginx to start
        run: sleep 5

      - name: Debug Nginx response
        run: |
          curl -s http://localhost:8080/

      - name: Test Hello World Page
        run: |
          curl -s -o response.html http://localhost:8080/
          grep "Hello World" response.html

      - name: Stop Nginx container
        run: docker stop test-nginx
